---
- name: Configuração da VM com Insomnia e VNC
  hosts: localhost 
  become: true
  become_method: sudo

  vars:
    ansible_python_interpreter: /usr/bin/python3
    vnc_password: "password"

  tasks:
    - name: Atualizar os repositórios e pacotes
      apt:
        update_cache: yes

    - name: Instalar ambiente gráfico (Ubuntu GNOME)
      apt:
        name: ubuntu-desktop
        state: present

    - name: Instalar o servidor SSH
      apt:
        name: openssh-server
        state: present

    - name: Instalar servidor VNC
      apt:
        name: tightvncserver
        state: present

    - name: Criar arquivo temporário de senha VNC
      copy:
        content: "{{ vnc_password }}\n{{ vnc_password }}\n\n"
        dest: "/tmp/vncpass"
        mode: '0600'

    - name: Configurar senha VNC sem interação
      command: "vncpasswd -f < /tmp/vncpass"
      become: yes

    - name: Remover arquivo temporário de senha VNC
      file:
        path: "/tmp/vncpass"
        state: absent

    - name: Criar arquivo xstartup do VNC
      copy:
        dest: /home/{{ ansible_user }}/.vnc/xstartup
        content: |
          #!/bin/sh
          exec /etc/X11/xinit/xinitrc
        mode: '0755'

    - name: Iniciar o servidor VNC
      shell: vncserver :1

    - name: Baixar pacote Insomnia
      get_url:
        url: https://updates.insomnia.rest/downloads/ubuntu/latest?&app=com.insomnia.app&source=website
        dest: /tmp/insomnia.deb

    - name: Instalar Insomnia
      apt:
        deb: /tmp/insomnia.deb
      ignore_errors: yes

    - name: Remover pacote baixado do Insomnia
      file:
        path: /tmp/insomnia.deb
        state: absent