---
- name: Configuração da VM com Insomnia e VNC
  hosts: localhost
  become: true
  become_method: sudo
  remote_user: ubuntu
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    vnc_password: "password"

  tasks:
    - name: Atualizar os repositórios e pacotes
      apt:
        update_cache: yes

    - name: Instalar ambiente gráfico (Ubuntu GNOME)
      apt:
        name: ubuntu-desktop
        state: present

    - name: Instalar o servidor SSH
      apt:
        name: openssh-server
        state: present

    - name: Instalar servidor VNC
      apt:
        name: tightvncserver
        state: present

    - name: Definir senha do VNC sem interação
      expect:
        command: vncpasswd
        responses:
          "Password:": "{{ vnc_password }}"
          "Verify:": "{{ vnc_password }}"
          "Would you like to enter a view-only password (y/n)?": "n"
      become: yes
      when: vnc_password is defined

    - name: Criar diretório .vnc
      file:
        path: /home/{{ ansible_user_id }}/.vnc
        state: directory
        mode: '0755'

    - name: Criar arquivo xstartup do VNC
      copy:
        dest: /home/{{ ansible_user_id }}/.vnc/xstartup
        content: |
          #!/bin/sh
          exec /etc/X11/xinit/xinitrc
        mode: '0755'

    - name: Parar o servidor VNC se estiver rodando
      shell: "vncserver -kill :1"
      ignore_errors: yes

    - name: Iniciar o servidor VNC
      shell: vncserver :1
      become: yes

    - name: Baixar pacote Insomnia
      get_url:
        url: https://updates.insomnia.rest/downloads/ubuntu/latest?&app=com.insomnia.app&source=websi>       
        dest: /tmp/insomnia.deb

    - name: Instalar Insomnia
      apt:
        deb: /tmp/insomnia.deb
      ignore_errors: yes

    - name: Iniciar o Insomnia na sessão VNC
      shell: |
        export DISPLAY=:1
        nohup insomnia > /dev/null 2>&1 &
      become: yes

    - name: Remover pacote baixado do Insomnia
      file:
        path: /tmp/insomnia.deb
        state: absent