---
- hosts: backend
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    backend_image: "norohim/cp-planta-backend:latest"  
    backend_port: 3000 
    postgres_port: 5432
    postgres_user: "postgres"
    postgres_password: "postgres"
    postgres_db: "postgres"
  tasks:
    - name: Update apt cache and install dependencies
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
          - python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker network
      community.docker.docker_network:
        name: app_network  # Rede para todos os contêineres

    - name: Pull Backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Run Backend container
      community.docker.docker_container:
        name: backend
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        networks:
          - name: app_network
        env: 
          DB_HOST: "postgres"
          DB_PORT: "{{ postgres_port }}"
          DB_USER: "{{ postgres_user }}"
          DB_PASSWORD: "{{ postgres_password }}"
          DB_NAME: "{{ postgres_db }}"
