---
- name: Deploy Frontend Application
  hosts: frontend  # Update to match your frontend VM group or host in the inventory
  become: yes
  vars:
    docker_image: "norohim/cp-planta-frontend:latest"  # Replace with your frontend Docker image
    container_name: "frontend-app"
    container_port: 3001  # Replace with the port your frontend app uses
    host_port: 3001  # Port to expose on the host

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Frontend Docker Image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop and Remove Existing Container if Exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes
        ignore_errors: yes

    - name: Run Frontend Docker Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"
        env:
          NODE_ENV: "production"  # Add other environment variables if necessary
