---
- hosts: database
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    postgres_user: "postgres"
    postgres_password: "postgres"
    postgres_db: "postgres"
    postgres_exporter_user: "postgres_exporter"
    postgres_exporter_password: "postgres_exporter"
    postgres_port: 5432
    postgres_exporter_port: 9187
  tasks:
    - name: Update apt cache and install dependencies
      apt:
        update_cache: yes
        name:
          - docker.io
          - docker-compose
          - python3-pip
          - python3-psycopg2
        state: present

    - name: Pull PostgreSQL Exporter image
      community.docker.docker_image:
        name: quay.io/prometheuscommunity/postgres-exporter
        source: pull

    - name: Run PostgreSQL Exporter container
      community.docker.docker_container:
        name: postgres_exporter
        image: quay.io/prometheuscommunity/postgres-exporter
        state: started
        restart_policy: always
        env:
          DATA_SOURCE_NAME: "postgresql://{{ postgres_user }}:{{ postgres_password }}@postgres:{{ postgres_port }}/{{ postgres_db }}?sslmode=disable"
        ports:
          - "{{ postgres_exporter_port }}:{{ postgres_exporter_port }}"
        networks:
          - name: app_network

    - name: Wait for PostgreSQL to be ready
      wait_for:
        port: "{{ postgres_port }}"
        host: "database"
        timeout: 10

    - name: Clean up SQL scripts from VM
      file:
        path: "/tmp/db_scripts/"
        state: absent

    - name: Create PostgreSQL user for exporter
      community.postgresql.postgresql_user:
        name: "{{ postgres_exporter_user }}"
        password: "{{ postgres_exporter_password }}"
        db: "{{ postgres_db }}"
        state: present
        login_host: "database"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        login_port: "{{ postgres_port }}"

    - name: Grant SELECT on pg_stat_database to the PostgreSQL exporter user
      community.postgresql.postgresql_privs:
        db: "{{ postgres_db }}"
        role: "{{ postgres_exporter_user }}"
        type: table
        privs: "SELECT"
        objs: "pg_stat_database"
        schema: "pg_catalog"
        state: present
        login_host: "database"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        login_port: "{{ postgres_port }}"

    - name: Grant SELECT on pg_stat_activity to the PostgreSQL exporter user
      community.postgresql.postgresql_privs:
        db: "{{ postgres_db }}"
        role: "{{ postgres_exporter_user }}"
        type: table
        privs: "SELECT"
        objs: "pg_stat_activity"
        schema: "pg_catalog"
        state: present
        login_host: "database"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        login_port: "{{ postgres_port }}"

    - name: Grant SELECT on pg_stat_replication to the PostgreSQL exporter user
      community.postgresql.postgresql_privs:
        db: "{{ postgres_db }}"
        role: "{{ postgres_exporter_user }}"
        type: table
        privs: "SELECT"
        objs: "pg_stat_replication"
        schema: "pg_catalog"
        state: present
        login_host: "database"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        login_port: "{{ postgres_port }}"