---
- hosts: all
  become: yes
  vars:
    gitlab_runner_url: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
    gitlab_runner_config_dir: "/etc/gitlab-runner"
    gitlab_runner_path: "/usr/local/bin/gitlab-runner"
    gitlab_runner_registration_url: "{{ lookup('env', 'CI_SERVER_URL') }}"
    gitlab_runner_registration_token: "{{ lookup('env', 'RUNNER_TOKEN') }}"
    gitlab_runner_executor: "docker"
    gitlab_runner_docker_image: "docker:latest"
    gitlab_runner_description: "AWS Runner VM on {{ ansible_host }}"
    gitlab_runner_tags: "aws,docker,runner-on-{{ ansible_host }}"
    gitlab_runner_user: "gitlab-runner"

  tasks:
    - name: Download GitLab Runner binary
      get_url:
        url: "{{ gitlab_runner_url }}"
        dest: "{{ gitlab_runner_path }}"
        mode: '0755'

    - name: Create GitLab Runner config directory
      file:
        path: "{{ gitlab_runner_config_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ gitlab_runner_user }}"
        group: "{{ gitlab_runner_user }}"

    - name: Ensure GitLab Runner temporary directory exists
      file:
        path: /home/gitlab-runner/.ansible/tmp
        state: directory
        owner: gitlab-runner
        group: gitlab-runner
        mode: '0755'

    - name: Register GitLab Runner
      command: >
        {{ gitlab_runner_path }} register
        --non-interactive
        --url "{{ gitlab_runner_registration_url }}"
        --registration-token "{{ gitlab_runner_registration_token }}"
        --executor "{{ gitlab_runner_executor }}"
        --docker-image "{{ gitlab_runner_docker_image }}"
        --description "{{ gitlab_runner_description }}"
        --tag-list "{{ gitlab_runner_tags }}"
        --run-untagged
        --locked=false
        --docker-privileged
      environment:
        HOME: "/home/{{ gitlab_runner_user }}"
      args:
        creates: "{{ gitlab_runner_config_dir }}/config.toml"
      become_user: "{{ gitlab_runner_user }}"
      notify: restart gitlab-runner

    - name: Modify config.toml to add custom Docker options
      ini_file:
        path: "{{ gitlab_runner_config_dir }}/config.toml"
        section: "runners.docker"
        option: "allowed_images"
        value: '["docker:*"]' 

    - name: Ensure correct permissions for GitLab Runner config.toml
      file:
        path: "{{ gitlab_runner_config_dir }}/config.toml"
        state: file
        mode: '0644'
        owner: "{{ gitlab_runner_user }}"
        group: "{{ gitlab_runner_user }}"
      become: yes

    - name: Install GitLab Runner service
      command: "{{ gitlab_runner_path }} install --user {{ gitlab_runner_user }}"
      args:
        creates: "/etc/systemd/system/gitlab-runner.service"
      notify: restart gitlab-runner

    - name: Start GitLab Runner service
      systemd:
        name: gitlab-runner
        state: started
        enabled: true

  handlers:
    - name: restart gitlab-runner
      systemd:
        name: gitlab-runner
        state: restarted