---
- hosts: all
  become: yes
  vars:
    gitlab_runner_image: "gitlab/gitlab-runner:latest"
    gitlab_runner_service_name: "gitlab-runner"
    gitlab_runner_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/gitlab-runner/config:/etc/gitlab-runner"
    gitlab_runner_environment:
      CI_SERVER_URL: "{{ lookup('env', 'CI_SERVER_URL') }}"
      RUNNER_TOKEN: "{{ lookup('env', 'RUNNER_TOKEN') }}"

  tasks:
    - name: Ensure Docker is installed on all nodes
      apt:
        name: 
          - docker.io
        state: present
        update_cache: yes

    - name: Create GitLab Runner config directory on host
      file:
        path: "/srv/gitlab-runner/config"
        state: directory
        mode: '0755'

    - name: Deploy GitLab Runner on Docker Swarm
      docker_service:
        project_name: "{{ gitlab_runner_service_name }}"
        definition:
          version: '3.8'
          services:
            runner:
              image: "{{ gitlab_runner_image }}"
              environment:
                - CI_SERVER_URL={{ gitlab_runner_environment.CI_SERVER_URL }}
                - RUNNER_TOKEN={{ gitlab_runner_environment.RUNNER_TOKEN }}
              volumes:
                - "{{ gitlab_runner_volumes[0] }}"
                - "{{ gitlab_runner_volumes[1] }}"
              deploy:
                mode: replicated
                replicas: 4
                restart_policy:
                  condition: on-failure
        networks:
          - runner_network

    - name: Ensure runner network is created
      docker_network:
        name: runner_network
        state: present

    - name: Set concurrent = 2 in config.toml
      lineinfile:
        path: "/srv/gitlab-runner/config/config.toml"
        regexp: '^concurrent = '
        line: 'concurrent = 2'
        state: present

    - name: Update GitLab Runner config.toml for bash executor
      lineinfile:
        path: "/srv/gitlab-runner/config/config.toml"
        regexp: '^  shell = '
        line: '  shell = "/bin/bash"'
        state: present

    - name: Set disable_profile_loading to true in config.toml
      lineinfile:
        path: "/srv/gitlab-runner/config/config.toml"
        regexp: '^  disable_profile_loading = '
        line: '  disable_profile_loading = true'
        state: present